import { useEffect,useState,useRef } from 'react';
import { Archive,Download,Upload,Check,Eye,ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { adminApi } from '@/lib/adminApi';
import { AdminAssetImage } from './AdminAssetImage';

export const AdminDecorationLibrary=({onChoose})=>{
  const [items,setItems]=useState([]),[name,setName]=useState(''),[file,setFile]=useState(null),[review,setReview]=useState(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const input=useRef();const load=()=>adminApi('/decorations').then(setItems).catch(e=>setError(e.message));
  useEffect(()=>{load();},[]);
  const run=async fn=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const upload=()=>run(async()=>{if(!file||!name.trim())throw new Error('Bitte Name und Datei angeben.');if(file.size>8*1024*1024)throw new Error('Bitte höchstens 8 MB auswählen.');const body=new FormData();body.append('file',file);body.append('name',name);const item=await adminApi('/decorations/upload',{method:'POST',body});setReview(item);setConfirmed(false);setName('');setFile(null);input.current.value='';});
  const confirm=()=>run(async()=>{await adminApi(`/decorations/${review.id}/confirm`,{method:'POST',body:{confirmed:true}});setReview(null);});
  const download=item=>run(async()=>{const blob=await adminApi(`/decorations/${item.id}/original`,{blob:true});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${item.name}.${item.mime==='image/svg+xml'?'svg':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  return <section className="admin-library" data-testid="admin-decoration-library">
    {!onChoose&&<Link to="/verwaltung" className="studio-text-link" data-testid="library-back"><ArrowLeft size={16}/>Artikelverwaltung</Link>}
    <div className="admin-section-heading"><div><p className="eyebrow">EIGENE MOTIVE</p><h1>Dekorationsbibliothek</h1></div></div>
    {!onChoose&&<div className="library-upload"><label>Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} data-testid="decoration-upload-name"/></label><label>Datei<input ref={input} type="file" accept="image/png,image/svg+xml,.svg" onChange={e=>setFile(e.target.files?.[0]||null)} data-testid="decoration-upload-file"/></label><Button type="button" disabled={busy||!file||name.trim().length<2} onClick={upload} data-testid="decoration-upload-submit"><Upload size={16}/>{busy?'Wird geprüft …':'Hochladen & prüfen'}</Button><p>Transparentes PNG oder statisches SVG · max. 8 MB / PNG max. 20 Megapixel. SVG-Schriftzüge als Pfade; keine Bilder, Verweise, Animationen oder Filter.</p></div>}
    {error&&<p role="alert" className="studio-error" data-testid="library-error">{error}</p>}
    <div className="library-grid">{items.filter(i=>onChoose?i.confirmed&&i.state!=='archived':true).map(item=><article key={item.id} data-testid={`library-item-${item.id}`}><div className="transparency-preview"><AdminAssetImage id={item.id} alt={item.name} testId={`library-preview-${item.id}`}/></div><strong data-testid={`library-name-${item.id}`}>{item.name}</strong><span data-testid={`library-state-${item.id}`}>{item.state==='published'?'Veröffentlicht':item.state==='archived'?'Archiviert':item.confirmed?'Entwurf · bestätigt':'Darstellung prüfen'}</span>{onChoose?<Button type="button" onClick={()=>onChoose(item)} data-testid={`library-use-${item.id}`}>Motiv verwenden</Button>:<div className="library-actions"><button type="button" title="Darstellung prüfen" aria-label="Darstellung prüfen" onClick={()=>{setReview(item);setConfirmed(item.confirmed);}} data-testid={`library-review-${item.id}`}><Eye size={16}/></button><button type="button" title="Original herunterladen" aria-label="Original herunterladen" disabled={busy} onClick={()=>download(item)} data-testid={`library-download-${item.id}`}><Download size={16}/></button><button type="button" disabled={busy||!item.confirmed} onClick={()=>run(()=>adminApi(`/decorations/${item.id}/publish`,{method:'POST'}))} data-testid={`library-publish-${item.id}`}><Check size={15}/>{item.state==='published'?'Erneut veröffentlichen':'Veröffentlichen'}</button>{item.state!=='archived'&&<button type="button" disabled={busy} title="Archivieren" aria-label="Archivieren" onClick={()=>run(()=>adminApi(`/decorations/${item.id}/archive`,{method:'POST'}))} data-testid={`library-archive-${item.id}`}><Archive size={16}/></button>}</div>}</article>)}</div>
    {!items.length&&<p data-testid="library-empty">Noch keine eigenen Dekorationen vorhanden.</p>}
    <Dialog open={!!review} onOpenChange={v=>{if(!v&&!busy)setReview(null);}}><DialogContent className="decoration-review" data-testid="decoration-review"><DialogTitle>Einfarbige Darstellung prüfen</DialogTitle><DialogDescription>Deckende Bereiche werden graviert. Weiß wird nicht transparent; keine automatische Freistellung oder Produktionsfreigabe.</DialogDescription>{review&&<><div className="transparency-preview"><AdminAssetImage id={review.id} alt={review.name} testId="decoration-review-image"/></div><label>Name<input value={review.name} onChange={e=>setReview({...review,name:e.target.value})} maxLength={80} data-testid="decoration-review-name"/></label><label className="admin-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} data-testid="decoration-review-confirm"/>Ich bestätige die Darstellung und die Nutzungsrechte.</label><Button type="button" disabled={!confirmed||busy||review.name.trim().length<2} onClick={()=>run(async()=>{await adminApi(`/decorations/${review.id}`,{method:'PATCH',body:{name:review.name}});await adminApi(`/decorations/${review.id}/confirm`,{method:'POST',body:{confirmed:true}});setReview(null);})} data-testid="decoration-review-save">In Bibliothek übernehmen</Button></>}</DialogContent></Dialog>
  </section>;
};