import { useRef, useState } from 'react';
import { ArrowLeft, Save, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { BlankAreaEditor } from './BlankAreaEditor';
import { adminApi } from '@/lib/adminApi';

const initial = { name: '', subtitle: '', material: 'Holz', category: 'holz', price_cents: 2490, dimensions: '', area_mm: '', max_text: 30, area: { x: 250, y: 250, w: 300, h: 300, shape: 'rect' }, ink: '#493627', templates: ['text','photo','logo'], image_file_id: null, image: '', active: true, is_sample: false, version: 1 };
export const BlankForm = ({ product, onClose, onSaved }) => {
  const [form, setForm] = useState(product || initial), [busy, setBusy] = useState(false), [error, setError] = useState(''), input = useRef();
  const update = values => setForm(old => ({ ...old, ...values }));
  const upload = async file => { if (!file) return; setBusy(true); setError(''); try { const body = new FormData(); body.append('file', file); const result = await adminApi('/products/photo', { method: 'POST', body }); update({ image: result.image, image_file_id: result.id }); } catch (e) { setError(e.message); } finally { setBusy(false); input.current.value = ''; } };
  const save = async e => { e.preventDefault(); setBusy(true); setError(''); try { const { id, image, production_approved, ...body } = form; const saved = await adminApi(`/products${id ? '/' + id : ''}`, { method: id ? 'PUT' : 'POST', body }); onSaved(saved); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <form onSubmit={save} className="blank-form"><div className="admin-section-heading"><button type="button" className="studio-text-link" onClick={onClose} disabled={busy} data-testid="admin-back-list"><ArrowLeft size={16} />Alle Rohlinge</button><h2>{product ? product.name : 'Neuer Rohling'}</h2><Button type="submit" disabled={busy || !form.image || !form.templates.length} data-testid="admin-save-product"><Save size={16} />{busy ? 'Wird verarbeitet …' : 'Rohling speichern'}</Button></div>
    <fieldset disabled={busy} className="blank-form-grid"><section><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={e => upload(e.target.files?.[0])} className="sr-only" data-testid="admin-photo-input" /><button type="button" className="admin-photo-upload" onClick={() => input.current.click()} data-testid="admin-upload-photo"><Upload size={17} />{form.image ? 'Rohlingfoto ersetzen' : 'Rohlingfoto hochladen'}<small>JPG, PNG, WebP · max. 8 MB · öffentliches Produktfoto</small></button>{form.image ? <BlankAreaEditor image={form.image} area={form.area} onChange={area => update({ area })} /> : <div className="admin-photo-placeholder" data-testid="admin-photo-placeholder"><Upload size={32} />Dein ungravierter Rohling</div>}</section>
    <section className="blank-fields"><h2>Produkt & Gravur</h2>{[['name','Produktname',80],['material','Material',50],['dimensions','Produktmaße (mm)',80],['area_mm','Gravurfläche (mm)',80]].map(([key,label,max]) => <label key={key} htmlFor={`blank-${key}`}>{label}<Input id={`blank-${key}`} required maxLength={max} value={form[key]} onChange={e => update({ [key]: e.target.value })} data-testid={`blank-${key}`} /></label>)}<label htmlFor="blank-category">Kategorie<select id="blank-category" value={form.category} onChange={e => update({ category: e.target.value })} data-testid="blank-category">{[['holz','Holz'],['glas','Glas'],['metall','Metall'],['kunststoff','Kunststoff'],['schiefer','Schiefer'],['textil','Textil']].map(([id,label]) => <option value={id} key={id}>{label}</option>)}</select></label><div className="blank-two"><label>Beispielpreis (€)<Input type="number" required min="0" max="10000" step="0.01" value={form.price_cents / 100} onChange={e => update({ price_cents: Math.round(Number(e.target.value) * 100) })} data-testid="blank-price" /></label><label>Max. Textzeichen<Input type="number" required min="1" max="60" value={form.max_text} onChange={e => update({ max_text: Number(e.target.value) })} data-testid="blank-max-text" /></label></div><label>Gravurfarbe<input type="color" value={form.ink} onChange={e => update({ ink: e.target.value })} data-testid="blank-ink" /></label><fieldset className="blank-checks"><legend>Erlaubte Vorlagen</legend>{[['text','Text'],['photo','Foto & Text'],['logo','Logo & Text']].map(([id,label]) => <label key={id}><input type="checkbox" checked={form.templates.includes(id)} onChange={e => update({ templates: e.target.checked ? [...form.templates,id] : form.templates.filter(t => t !== id) })} data-testid={`blank-template-${id}`} />{label}</label>)}</fieldset><label className="blank-checkbox"><input type="checkbox" checked={form.is_sample} onChange={e => update({ is_sample: e.target.checked })} data-testid="blank-sample" />Als Musterrohling kennzeichnen</label><label className="blank-checkbox"><input type="checkbox" checked={form.active} onChange={e => update({ active: e.target.checked })} data-testid="blank-active" />Im Gestaltungsstudio sichtbar</label><p className="admin-test-notice" data-testid="admin-test-notice">Testmodus bleibt aktiv. Ein gespeicherter Rohling ist keine Fertigungsfreigabe.</p></section></fieldset>{error && <p className="studio-error" role="alert" data-testid="admin-form-error">{error}</p>}
  </form>;
};