import { useRef,useState } from 'react';
import { ArrowLeft,Save,Upload,Package,Scan,LayoutTemplate } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { BlankAreaEditor } from './BlankAreaEditor';
import { ArticleTemplates } from './ArticleTemplates';
import { adminApi } from '@/lib/adminApi';
import { productImage } from '@/lib/studioApi';
import { useSearchParams } from 'react-router-dom';

const initial={name:'',subtitle:'',material:'Holz',category:'holz',price_cents:2490,dimensions:'',area_mm:'',max_text:30,area:{x:250,y:250,w:300,h:300,shape:'rect'},exclusions:[],ink:'#493627',templates:['text','photo','logo'],image_file_id:null,image:'',active:true,is_sample:false,version:1,show_basic_templates:true,decoration_ids:[]};
export const BlankForm=({product,onClose,onSaved})=>{
  const [params]=useSearchParams();
  const [form,setForm]=useState({...initial,...product}),[tab,setTab]=useState(params.get('tab')==='templates'?'templates':'info'),[busy,setBusy]=useState(false),[error,setError]=useState('');const input=useRef();
  const update=values=>setForm(old=>({...old,...values}));
  const upload=async file=>{if(!file)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const result=await adminApi('/products/photo',{method:'POST',body});update({image:result.image,image_file_id:result.id});}catch(e){setError(e.message);}finally{setBusy(false);input.current.value='';}};
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const {id,image,production_approved,...body}=form;const saved=await adminApi(`/products${id?'/'+id:''}`,{method:id?'PUT':'POST',body});setForm({...initial,...saved});onSaved(saved);}catch(err){setError(err.message);}finally{setBusy(false);}};
  return <form onSubmit={save} className="blank-form"><div className="admin-section-heading"><button type="button" className="studio-text-link" onClick={onClose} disabled={busy} data-testid="admin-back-list"><ArrowLeft size={16}/>Alle Artikel</button><h2>{form.name||'Neuer Artikel'}</h2><Button type="submit" disabled={busy||!form.image||!form.templates.length} data-testid="admin-save-product"><Save size={16}/>{busy?'Wird gespeichert …':'Artikel speichern'}</Button></div>
    <nav className="admin-product-tabs" aria-label="Artikelbereiche">{[['info',Package,'Artikeldaten'],['area',Scan,'Gravurfläche'],['templates',LayoutTemplate,'Vorlagen']].map(([id,Icon,label])=><button type="button" key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} data-testid={`admin-product-tab-${id}`}><Icon size={17}/>{label}</button>)}</nav>
    {error&&<p className="studio-error" role="alert" data-testid="admin-form-error">{error}</p>}
    {tab==='templates'?(product?<ArticleTemplates product={product} showBasics={form.show_basic_templates} decorationIds={form.decoration_ids} onSettings={update}/>:<p data-testid="admin-save-article-first">Bitte den Artikel zuerst speichern.</p>):<fieldset disabled={busy} className="blank-form-grid"><section><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])} className="sr-only" data-testid="admin-photo-input"/>{tab==='info'&&<button type="button" className="admin-photo-upload" onClick={()=>input.current.click()} data-testid="admin-upload-photo"><Upload size={17}/>{form.image?'Rohlingfoto ersetzen':'Rohlingfoto hochladen'}<small>JPG, PNG, WebP · max. 8 MB · öffentliches Produktfoto</small></button>}{form.image?tab==='area'?<BlankAreaEditor image={form.image} area={form.area} exclusions={form.exclusions} onChange={area=>update({area})} onExclusionsChange={exclusions=>update({exclusions})}/>:<img className="admin-article-photo" src={productImage(form.image)} alt={form.name||'Rohlingfoto'} data-testid="admin-article-photo"/>:<div className="admin-photo-placeholder" data-testid="admin-photo-placeholder"><Upload size={32}/>Dein ungravierter Rohling</div>}</section>
    <section className="blank-fields">{tab==='info'?<><h2>Artikeldaten</h2>{[['name','Artikelname',80],['material','Material',50],['dimensions','Produktmaße (mm)',80]].map(([key,label,max])=><label key={key} htmlFor={`blank-${key}`}>{label}<Input id={`blank-${key}`} required maxLength={max} value={form[key]} onChange={e=>update({[key]:e.target.value})} data-testid={`blank-${key}`}/></label>)}<label htmlFor="blank-category">Materialgruppe<select id="blank-category" value={form.category} onChange={e=>update({category:e.target.value})} data-testid="blank-category">{[['holz','Holz'],['glas','Glas'],['metall','Metall'],['kunststoff','Kunststoff'],['schiefer','Schiefer'],['textil','Textil']].map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Beispielpreis (€)<Input type="number" required min="0" max="10000" step="0.01" value={form.price_cents/100} onChange={e=>update({price_cents:Math.round(Number(e.target.value)*100)})} data-testid="blank-price"/></label><label className="blank-checkbox"><input type="checkbox" checked={form.is_sample} onChange={e=>update({is_sample:e.target.checked})} data-testid="blank-sample"/>Als Musterrohling kennzeichnen</label><label className="blank-checkbox"><input type="checkbox" checked={form.active} onChange={e=>update({active:e.target.checked})} data-testid="blank-active"/>Im Gestaltungsstudio sichtbar</label></>:<><h2>Gravurfläche</h2><p className="admin-measure-note" data-testid="admin-coordinate-note">Position und Größe auf dem Foto: Pixel. Tatsächliche Gravurmaße: Millimeter, separat gemessen.</p><label htmlFor="blank-area_mm">{form.area.shape==='circle'?'Realer Gravurdurchmesser (mm)':'Reale Gravurfläche B × H (mm)'}<Input id="blank-area_mm" required maxLength={80} placeholder={form.area.shape==='circle'?'z. B. Ø 80 mm':'z. B. 120 × 80 mm'} value={form.area_mm} onChange={e=>update({area_mm:e.target.value})} data-testid="blank-area_mm"/></label><label>Max. Textzeichen<Input type="number" required min="1" max="60" value={form.max_text} onChange={e=>update({max_text:Number(e.target.value)})} data-testid="blank-max-text"/></label><label>Gravurfarbe<input type="color" value={form.ink} onChange={e=>update({ink:e.target.value})} data-testid="blank-ink"/></label><fieldset className="blank-checks"><legend>Erlaubte Inhalte</legend>{[['text','Text'],['photo','Foto'],['logo','Logo']].map(([id,label])=><label key={id}><input type="checkbox" checked={form.templates.includes(id)} onChange={e=>update({templates:e.target.checked?[...form.templates,id]:form.templates.filter(t=>t!==id)})} data-testid={`blank-template-${id}`}/>{label}</label>)}</fieldset><p className="admin-measure-note" data-testid="area-template-recheck-note">Geänderte Grenzen werden vor neuen Gestaltungen und dem Testabschluss erneut geprüft. Bestehende Entwürfe werden nicht automatisch angepasst.</p></>}<p className="admin-test-notice" data-testid="admin-test-notice">Testmodus · keine Fertigungsfreigabe.</p></section></fieldset>}
  </form>;
};