import { useEffect, useRef, useState } from 'react';
import ReactCrop from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';

export const CropDialog = ({ url, element, onClose, onApply }) => {
  const [crop, setCrop] = useState({ unit: '%', x: element.crop.x * 100, y: element.crop.y * 100, width: element.crop.w * 100, height: element.crop.h * 100 }), img = useRef(), wrap = useRef();
  const [ratio, setRatio] = useState('free');
  useEffect(() => { wrap.current?.querySelectorAll('[role="slider"],button').forEach((node,i) => node.setAttribute('data-testid', `crop-handle-${i}`)); }, [crop]);
  const apply = () => { if (!img.current?.naturalWidth || crop.width < 1 || crop.height < 1) return; onApply({ x: crop.x / 100, y: crop.y / 100, w: crop.width / 100, h: crop.height / 100 }, (crop.height * img.current.naturalHeight) / (crop.width * img.current.naturalWidth)); };
  return <Dialog open onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="crop-dialog" data-testid="crop-dialog"><DialogTitle>Dein Bildausschnitt</DialogTitle><DialogDescription>Das Original bleibt erhalten.</DialogDescription><div className="crop-ratios">{[['free','Frei'],['1','Quadrat'],['1.333333','4:3']].map(([id,label]) => <button key={id} onClick={() => { setRatio(id); if (img.current && id !== 'free') { const width = Math.min(90, 90 * Number(id) * img.current.naturalHeight / img.current.naturalWidth); setCrop({ unit: '%', x: (100 - width) / 2, y: 5, width, height: width / Number(id) * img.current.naturalWidth / img.current.naturalHeight }); } }} aria-pressed={ratio === id} data-testid={`crop-ratio-${id}`}>{label}</button>)}</div><div className="crop-image-wrap" ref={wrap}><ReactCrop crop={crop} onChange={(_, percent) => setCrop(percent)} aspect={ratio === 'free' ? undefined : Number(ratio)} minWidth={10} minHeight={10}><img ref={img} src={url} alt="Motiv zum Zuschneiden" data-testid="crop-source-image" /></ReactCrop></div><div className="element-numbers">{[['x','Links'],['y','Oben'],['width','Breite'],['height','Höhe']].map(([key,label]) => <label key={key}>{label} (%)<input type="number" min="0" max="100" value={Math.round(crop[key] * 10) / 10} onChange={e => { const next = { ...crop, [key]: Number(e.target.value) }; next.width = Math.max(1, Math.min(next.width, 100 - next.x)); next.height = Math.max(1, Math.min(next.height, 100 - next.y)); next.x = Math.max(0, Math.min(99, next.x)); next.y = Math.max(0, Math.min(99, next.y)); setRatio('free'); setCrop(next); }} data-testid={`crop-percent-${key}`} /></label>)}</div><div className="crop-footer"><Button variant="outline" onClick={onClose} data-testid="crop-cancel">Abbrechen</Button><Button onClick={apply} disabled={crop.width < 1 || crop.height < 1} data-testid="crop-apply">Zuschnitt übernehmen</Button></div></DialogContent></Dialog>;
};