import { useEffect,useState } from 'react';
import { Stamp as Shapes } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { studioApi,productImage } from '@/lib/studioApi';

export const DecorationPicker=({disabled,onAdd,product})=>{
  const [open,setOpen]=useState(false),[items,setItems]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!open)return;let alive=true;setItems(null);setError('');studioApi(`/own-decorations?product_id=${product.id}`).then(data=>{if(alive)setItems(data.items);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[open,product.id]);
  const choose=async item=>{setBusy(true);try{await studioApi(`/own-decorations/${item.id}/use`,{method:'POST',body:{product_id:product.id}});onAdd(item);setOpen(false);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <><button className="editor-add-button decoration-trigger" disabled={disabled} title="Freigegebene eigene Motive" onClick={()=>setOpen(true)} data-testid="decoration-picker-open"><Shapes size={16}/><span>Dekoration</span></button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="decoration-dialog" data-testid="decoration-dialog"><DialogTitle>Eigene Motive</DialogTitle><DialogDescription>{product.name}</DialogDescription><div className="decoration-options">{items?.map(item=><button disabled={busy} key={item.id} data-testid={`add-decoration-${item.id}`} onClick={()=>choose(item)}><img loading="lazy" src={productImage(item.preview)} alt={item.name} data-testid={`decoration-thumbnail-${item.id}`}/><span>{item.name}</span></button>)}</div>{items?.length===0&&<p data-testid="decorations-empty">Für diesen Artikel sind keine eigenen Motive zum Hinzufügen freigegeben.</p>}{!items&&!error&&<p role="status" data-testid="decorations-loading">Motive laden …</p>}{error&&<p role="alert" data-testid="decoration-load-error">{error}</p>}</DialogContent></Dialog></>;
};