import { useEffect,useRef,useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Undo2,Redo2,Maximize2,Magnet,Type,ImagePlus,Shapes,LayoutTemplate,Layers,ChevronRight,Eye,Pencil,Spline,Copy,ArrowUpDown,LockKeyhole,LockKeyholeOpen,Trash2,Crop,Square,RefreshCw,MoreHorizontal,Save,ShoppingBag,LoaderCircle } from 'lucide-react';
import { studioApi,productImage,price } from '@/lib/studioApi';
import { imageFrame } from '@/lib/transformGeometry';
import { fullCrop } from '@/lib/studioLayers';
import { useStudioImage } from '@/hooks/useStudioImage';
import { DesignCanvas } from './DesignCanvas';
import { TemplatePicker } from './TemplatePicker';
import { BlankPicker } from './BlankPicker';
import { DecorationPicker } from './DecorationPicker';
import { CropDialog } from './CropDialog';
import { Sheet,Tiles,TextPanel,CurvePanel,LayersPanel,ImageAddPanel,ShapeFramePanel,MotifPanel } from './MobilePanels';
import { shapeNames } from '@/lib/studioShapes';
import '@/styles/studio-mobile.css';

const kindLabel=e=>e.kind==='text'?'Text':e.kind==='image'?'Bild':e.kind==='shape'?(shapeNames[e.shape_type]||'Form'):'Motiv';

export const MobileStudio=p=>{
  const {products,product,design,viewDesign,selected,select,active,commit,updateElement,addText,addImage,addShape,addDecoration,duplicate,remove,undo,redo,history,future,run,action,valid,canvasReady,canvasRef,saved,error,setError,editBusy,simple,onTemplate,naturalSize,setTextPending,setCart}=p;
  const navigate=useNavigate(),[panel,setPanel]=useState(null),[notice,setNotice]=useState(null),[snap,setSnap]=useState(true),[fitKey,setFitKey]=useState(0),[preview,setPreview]=useState(false),[crop,setCrop]=useState(false),[replace,setReplace]=useState(false);
  const source=useStudioImage(active?.kind==='image'?active.asset_id:null),undoRef=useRef(undo);undoRef.current=undo;
  const undoLatest=()=>undoRef.current();
  useEffect(()=>{document.body.classList.add('mobile-designer');return()=>document.body.classList.remove('mobile-designer');},[]);
  useEffect(()=>{if(!active)setPanel(old=>['object','text','curve','image-shape','motif'].includes(old)?null:old);},[active]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(null),4500);return()=>clearTimeout(t);},[notice]);
  const openSelection=id=>{select(id);setPanel('object');};
  const upload=async(file,target)=>{if(file.size>8*1024*1024){setError('Das Bild darf höchstens 8 MB groß sein.');return;}p.setAction('upload');try{const body=new FormData();body.append('file',file);body.append('rights_confirmed','true');const r=await studioApi('/uploads',{method:'POST',body});if(target)updateElement(target.id,imageFrame({...target,asset_id:r.id,original_asset_id:null,image_ratio:r.width/r.height,crop:fullCrop(),placeholder:false},r.width/r.height));else addImage(r);setPanel('object');setReplace(false);if(r.warning)setError(r.warning);}catch(e){setError(e.message);}finally{p.setAction('');}};
  const del=()=>{const label=kindLabel(active);remove(active.id);setPanel(null);setNotice({text:`${label} gelöscht`,undo:undoLatest});};
  const lock=()=>{updateElement(active.id,{locked:!active.locked});};
  const tiles=active&&(active.kind==='text'?[[Pencil,'Bearbeiten',()=>setPanel('text'),{disabled:active.locked}],[Spline,'Wölbung',()=>setPanel('curve'),{disabled:active.locked}],[Copy,'Duplizieren',()=>{duplicate(active.id);setNotice({text:'Kopie erstellt',undo:undoLatest});},{disabled:simple}],[ArrowUpDown,'Anordnen',()=>setPanel('layers'),{disabled:simple}],[active.locked?LockKeyholeOpen:LockKeyhole,active.locked?'Entsperren':'Sperren',lock,{disabled:simple}],[Trash2,'Löschen',del,{danger:true,disabled:simple||active.locked}]]
    :active.kind==='image'?[[Crop,'Zuschneiden',()=>setCrop(true),{disabled:active.locked||!source.url}],[Square,'Form',()=>setPanel('image-shape'),{disabled:active.locked}],[RefreshCw,'Ersetzen',()=>setReplace(true),{disabled:active.locked}],[ArrowUpDown,'Anordnen',()=>setPanel('layers'),{disabled:simple}],[active.locked?LockKeyholeOpen:LockKeyhole,active.locked?'Entsperren':'Sperren',lock,{disabled:simple}],[Trash2,'Löschen',del,{danger:true,disabled:simple||active.locked}],[MoreHorizontal,'Mehr',()=>setPanel('image-more'),{disabled:active.locked}]]
    :[[Pencil,'Bearbeiten',()=>setPanel('motif'),{disabled:active.locked||simple}],[Copy,'Duplizieren',()=>{duplicate(active.id);setNotice({text:'Kopie erstellt',undo:undoLatest});},{disabled:simple}],[ArrowUpDown,'Anordnen',()=>setPanel('layers'),{disabled:simple}],[active.locked?LockKeyholeOpen:LockKeyhole,active.locked?'Entsperren':'Sperren',lock,{disabled:simple}],[Trash2,'Löschen',del,{danger:true,disabled:simple||active.locked}]]);
  const toCart=async()=>{await run('cart');};
  const stage=(readOnly)=><div className="ms-stage"><DesignCanvas key={readOnly?'preview':`edit-${fitKey}`} product={product} design={viewDesign} guides={!readOnly} canvasRef={readOnly?undefined:canvasRef} updateElement={updateElement} selected={readOnly||simple?null:selected} onSelect={id=>id?openSelection(id):select(null)} disabled={editBusy||simple||readOnly} readOnly={readOnly} onReady={readOnly?undefined:p.setCanvasReady} onNaturalSize={naturalSize} snap={snap&&!readOnly} touchPan/>
    {!readOnly&&<div className="ms-stage-tools"><div><button type="button" onClick={undo} disabled={editBusy||!history.length} aria-label="Rückgängig" data-testid="ms-undo"><Undo2 size={19}/></button><button type="button" onClick={redo} disabled={editBusy||!future.length} aria-label="Wiederholen" data-testid="ms-redo"><Redo2 size={19}/></button></div><div><button type="button" aria-pressed={snap} onClick={()=>setSnap(v=>!v)} aria-label="Einrasthilfe" title="Einrasthilfe" data-testid="ms-snap-toggle"><Magnet size={18}/></button><button type="button" onClick={()=>setFitKey(k=>k+1)} aria-label="Ansicht einpassen" data-testid="ms-fit-view"><Maximize2 size={18}/></button></div></div>}
    {!readOnly&&!active&&!panel&&<p className="ms-hint" data-testid="ms-hint">Tippe ein Element zum Bearbeiten.</p>}</div>;
  return <main className="mobile-studio" data-testid="mobile-studio">
    <header className="ms-head"><strong>ManuCreator</strong><span data-state={saved?'saved':'dirty'} data-testid="ms-save-state">{saved?'Gespeichert':'Ungespeicherte Änderungen'}</span></header>
    <BlankPicker products={products} product={product} disabled={editBusy} onSelect={pr=>p.onProduct(pr)} trigger={<button type="button" className="ms-article" data-testid="ms-article"><img src={productImage(product.image)} alt=""/><span><b>{product.name}</b><small>{product.material} · {product.area_mm}</small></span><ChevronRight size={18}/></button>}/>
    {error&&<div className="precision-error" role="alert" data-testid="studio-error"><span>{error}</span><button onClick={()=>setError('')} aria-label="Meldung schließen" data-testid="studio-error-dismiss">×</button></div>}
    <div style={{position:'relative',flex:1,minHeight:0,display:'flex',flexDirection:'column'}}>{stage(false)}
      {notice&&<div className="ms-notice" role="status" data-testid="ms-notice"><span>{notice.text}</span>{notice.undo&&<button type="button" onClick={()=>{notice.undo();setNotice(null);}} data-testid="ms-notice-undo">Rückgängig</button>}</div>}
      {panel==='object'&&active&&<Sheet title={`${kindLabel(active)} ausgewählt`} onClose={()=>setPanel(null)} testId="ms-object-panel"><Tiles items={tiles} note="Verschieben: direkt auf dem Holz · Drehen über den Griff oberhalb der Auswahl"/></Sheet>}
      {panel==='text'&&active?.kind==='text'&&<Sheet title="Text bearbeiten" onClose={()=>setPanel('object')} testId="ms-text-panel"><TextPanel element={active} product={product} update={c=>updateElement(active.id,c)} onPending={setTextPending} disabled={editBusy}/></Sheet>}
      {panel==='curve'&&active?.kind==='text'&&<Sheet title="Wölbung" onClose={()=>setPanel('object')} testId="ms-curve-panel"><CurvePanel element={active} product={product} update={c=>updateElement(active.id,c)} onPending={setTextPending} disabled={editBusy}/></Sheet>}
      {panel==='image-shape'&&active?.kind==='image'&&<Sheet title="Form & Kanten" onClose={()=>setPanel('object')} testId="ms-image-shape-panel"><ShapeFramePanel element={active} update={c=>updateElement(active.id,c)} disabled={editBusy}/></Sheet>}
      {panel==='image-more'&&active?.kind==='image'&&<Sheet title="Weitere Einstellungen" onClose={()=>setPanel('object')} testId="ms-image-more-panel"><div className="ms-row"><button type="button" onClick={()=>updateElement(active.id,{x:product.area.x+(product.area.w-active.w)/2,y:product.area.y+(product.area.h-active.h)/2})} data-testid="ms-image-center">Zentrieren</button>{active.original_asset_id&&<button type="button" onClick={()=>updateElement(active.id,{asset_id:active.original_asset_id,original_asset_id:null})} data-testid="ms-image-restore">Original wiederherstellen</button>}</div><label className="ms-field">Drehung · {Math.round(active.rotation||0)}°<input type="range" min="-180" max="180" value={((active.rotation||0)+540)%360-180} onChange={ev=>updateElement(active.id,{rotation:Number(ev.target.value)})} data-testid="ms-image-rotation"/></label><p className="ms-tiles-note">Gravurvorschau wird direkt auf dem Produkt gezeigt. Freistellen ist ohne eingerichteten Dienst nicht verfügbar.</p></Sheet>}
      {panel==='motif'&&active&&<Sheet title={`${kindLabel(active)} bearbeiten`} onClose={()=>setPanel('object')} testId="ms-motif-panel"><MotifPanel element={active} product={product} update={c=>updateElement(active.id,c)} disabled={editBusy}/></Sheet>}
      {panel==='layers'&&<Sheet title="Reihenfolge" onClose={()=>setPanel(active?'object':null)} testId="ms-layers-panel"><LayersPanel elements={design.elements} selected={selected} onSelect={id=>select(id)} reorder={elements=>commit(c=>({...c,elements}))} updateElement={updateElement}/></Sheet>}
      {(panel==='image'||replace)&&<Sheet title={replace?'Bild ersetzen':'Bild hinzufügen'} onClose={()=>{setPanel(null);setReplace(false);}} testId="ms-image-panel"><ImageAddPanel disabled={editBusy||design.elements.length>=12} onFile={file=>upload(file,replace?active:null)}/></Sheet>}
      {panel==='motifs'&&<Sheet title="Motive" onClose={()=>setPanel(null)} testId="ms-motifs-panel"><p className="ms-tiles-note" style={{marginTop:0}}>Grundformen</p><Tiles items={Object.entries(shapeNames).map(([type,label])=>[Shapes,label,()=>{addShape(type);setPanel('object');}])}/><div className="ms-row" style={{marginTop:12}}><DecorationPicker product={product} disabled={editBusy||design.elements.length>=12} onAdd={item=>{addDecoration(item);setPanel('object');}}/></div></Sheet>}
      {panel==='templates'&&<Sheet title="Vorlagen" onClose={()=>setPanel(null)} testId="ms-templates-panel"><div className="ms-row"><TemplatePicker product={product} hasDesign={design.elements.length>0} disabled={editBusy} onApply={next=>{onTemplate(next);setPanel(null);}}/></div><p className="ms-tiles-note">Sechs schlichte Grundlagen und veröffentlichte Artikelvorlagen.</p></Sheet>}
      {crop&&active?.kind==='image'&&source.url&&<CropDialog element={active} url={source.url} onClose={()=>setCrop(false)} onApply={(value,ratio)=>{updateElement(active.id,imageFrame({...active,crop:value},1/ratio));setCrop(false);}}/>}
      {preview&&<section className="ms-preview" data-testid="ms-preview"><div className="ms-sheet-head"><h2>Deine Vorschau</h2><button type="button" onClick={()=>setPreview(false)} data-testid="ms-preview-edit"><Pencil size={15}/> Bearbeiten</button></div>{stage(true)}<div className="ms-article" style={{borderTop:'1px solid #dfe4d6'}}><img src={productImage(product.image)} alt=""/><span><b>{product.name}</b><small>{product.material} · {product.area_mm}</small></span></div><div className="ms-foot"><div><strong>{price(product.price_cents)}</strong><small>Beispielpreis · Testmodus</small></div><button type="button" className="ms-save" onClick={()=>run('save')} disabled={editBusy||!valid||!canvasReady} data-testid="ms-save"><Save size={16}/>Speichern</button><button type="button" onClick={toCart} disabled={editBusy||!valid||!canvasReady} data-testid="ms-add-cart">{action==='cart'?<LoaderCircle className="loading-spin" size={16}/>:<ShoppingBag size={16}/>}In den Warenkorb</button></div></section>}
    </div>
    <nav className="ms-bar" aria-label="Werkzeuge">{[[Type,'Text',()=>{if(simple)return;addText();setPanel('object');},'text'],[ImagePlus,'Bild',()=>setPanel('image'),'image'],[Shapes,'Motive',()=>setPanel('motifs'),'motifs'],[LayoutTemplate,'Vorlagen',()=>setPanel('templates'),'templates'],[Layers,'Ebenen',()=>setPanel('layers'),'layers']].map(([Icon,label,onClick,id])=><button type="button" key={id} onClick={onClick} aria-pressed={panel===id} disabled={editBusy||(simple&&['text','image','motifs'].includes(id))||(design.elements.length>=12&&['text','image','motifs'].includes(id))} data-testid={`ms-bar-${id}`}><Icon size={21}/>{label}</button>)}</nav>
    <footer className="ms-foot"><div><strong data-testid="ms-price">{price(product.price_cents)}</strong><small>Beispielpreis · Testmodus</small></div><button type="button" onClick={()=>{select(null);setPanel(null);setPreview(true);}} disabled={!canvasReady} data-testid="ms-preview-open"><Eye size={17}/>Vorschau</button></footer>
  </main>;
};
