import { useEffect,useState } from 'react';
import { LayoutTemplate,ArrowLeft,LoaderCircle } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { studioApi,productImage } from '@/lib/studioApi';

export const TemplatePicker=({product,hasDesign,disabled,onApply})=>{
  const [open,setOpen]=useState(false),[items,setItems]=useState(null),[chosen,setChosen]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!open)return;let alive=true;setItems(null);setError('');studioApi(`/templates?product_id=${encodeURIComponent(product.id)}`).then(data=>{if(alive)setItems(data.items);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[open,product.id]);
  const apply=async item=>{setBusy(true);setError('');try{const design=await studioApi(`/templates/${item.id}/apply`,{method:'POST',body:{product_id:product.id}});onApply(design);setOpen(false);setChosen(null);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <><button className="template-picker-trigger" disabled={disabled} onClick={()=>{setOpen(true);setChosen(null);}} data-testid="template-picker-open"><LayoutTemplate size={17}/><span>Vorlagen</span></button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="template-picker-dialog" data-testid="template-picker-dialog"><DialogTitle>{chosen?'Gestaltung ersetzen?':'Ein guter Anfang für dein Unikat'}</DialogTitle><DialogDescription>{chosen?'Die aktuelle Gestaltung wird durch diese Vorlage ersetzt. Rückgängig stellt den bisherigen Entwurf wieder her.':'Passend zur freigegebenen Gravurfläche deines Rohlings.'}</DialogDescription>{chosen?<div className="template-confirm"><img src={productImage(chosen.preview)} alt={chosen.name}/><strong>{chosen.name}</strong><Button disabled={busy} onClick={()=>apply(chosen)} data-testid="template-confirm-replace">{busy&&<LoaderCircle size={15} className="loading-spin"/>}Gestaltung ersetzen</Button><Button variant="outline" disabled={busy} onClick={()=>setChosen(null)} data-testid="template-confirm-cancel"><ArrowLeft size={14}/>Zurück</Button></div>:<div className="template-options">{items?items.length?items.map(item=><button key={item.id} onClick={()=>hasDesign?setChosen(item):apply(item)} disabled={busy} data-testid={`template-${item.id}`}><img src={productImage(item.preview)} alt={`Vorlage ${item.name} auf ${product.name}`}/><strong>{item.name}</strong><span>{item.subtitle}</span></button>):<p data-testid="templates-empty">Für diese Gravurfläche ist noch keine passende Vorlage verfügbar.</p>:<p role="status" data-testid="templates-loading">Vorlagen werden vorbereitet …</p>}</div>}{error&&<p className="property-error" role="alert" data-testid="template-error">{error}</p>}</DialogContent></Dialog></>;
};