import { isInside } from '@/lib/transformGeometry';
import { useState } from 'react';

export const TemplateFieldSettings=({element:e,product,update,disabled})=>{
  const [error,setError]=useState('');
  if(e.kind==='decoration'||e.kind==='shape')return null;
  const field=!!e.template_field,slot=e.template_slot||{x:e.x,y:e.y,w:e.w,h:e.h};
  const resize=(key,value)=>{const next={...slot,[key]:Math.max(1,Number(value))};next.x=e.x+e.w/2-next.w/2;next.y=e.y+e.h/2-next.h/2;if(!isInside(next,product.area,0)){setError('Das Kundenfeld muss innerhalb der Gravurfläche bleiben.');return;}setError('');update({template_slot:next});};
  return <fieldset className="admin-field-settings" disabled={disabled} data-testid="admin-field-settings"><h3>Kundenfreigabe</h3>{e.kind==='text'&&<label className="admin-check"><input type="checkbox" checked={field} onChange={event=>update(event.target.checked?{template_field:`field-${e.id.slice(0,12)}`,field_label:'Dein Text',field_max_length:product.max_text,template_slot:slot}:{template_field:null,field_label:null,template_slot:null,field_required:false})} data-testid="field-customer-editable"/>Als Kundenfeld bearbeiten</label>}{!field?<p data-testid="field-fixed-note">Fester Bestandteil der Vorlage</p>:<><label>Feldbezeichnung<input value={e.field_label||''} onChange={event=>update({field_label:event.target.value})} maxLength={60} data-testid="field-label"/></label>{e.kind==='text'&&<><label className="admin-check"><input type="checkbox" checked={!!e.field_required} onChange={event=>update({field_required:event.target.checked})} data-testid="field-required"/>Pflichtfeld</label><label>Maximale Zeichen<input type="number" min="1" max={product.max_text} value={e.field_max_length||product.max_text} onChange={event=>update({field_max_length:Math.max(1,Math.min(product.max_text,Number(event.target.value)))})} data-testid="field-max-length"/></label></>}<div className="element-numbers">{[['w','Feldbreite'],['h','Feldhöhe']].map(([key,label])=><label key={key}>{label} (px)<input type="number" min="1" max="800" value={Math.round(slot[key])} onChange={event=>resize(key,event.target.value)} data-testid={`field-slot-${key}`}/></label>)}</div></>}{error&&<p className="property-error" role="alert" data-testid="field-slot-error">{error}</p>}</fieldset>;
};