import { useEffect,useState } from 'react';
import { LayoutTemplate,ArrowLeft,LoaderCircle,Search } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { studioApi,productImage } from '@/lib/studioApi';

const labels={holz:'Holz',metall:'Metall',universell:'Universell'};
const normalized=s=>s.toLocaleLowerCase('de').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
export const TemplatePicker=({product,hasDesign,disabled,onApply})=>{
  const [open,setOpen]=useState(false),[items,setItems]=useState(null),[chosen,setChosen]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [search,setSearch]=useState(''),[collection,setCollection]=useState('all'),[occasion,setOccasion]=useState('all');
  useEffect(()=>{if(!open)return;let alive=true;setItems(null);setError('');studioApi(`/templates?product_id=${encodeURIComponent(product.id)}`).then(data=>{if(alive)setItems(data.items);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[open,product.id]);
  const apply=async item=>{setBusy(true);setError('');try{const design=await studioApi(`/templates/${item.id}/apply`,{method:'POST',body:{product_id:product.id}});onApply(design);setOpen(false);setChosen(null);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const filtered=(items||[]).filter(i=>(collection==='all'||i.collection===collection)&&(occasion==='all'||i.occasion===occasion)&&normalized(i.name).includes(normalized(search)));
  const collections=[...new Set((items||[]).map(i=>i.collection))];
  return <><button className="template-picker-trigger" disabled={disabled} onClick={()=>{setOpen(true);setChosen(null);setSearch('');setOccasion('all');setCollection('all');}} data-testid="template-picker-open"><LayoutTemplate size={17}/><span>Vorlagen</span></button>
    <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="template-picker-dialog" data-testid="template-picker-dialog">
      <DialogTitle>{chosen?'Gestaltung ersetzen?':'Dein Material. Dein Moment.'}</DialogTitle>
      <DialogDescription>{chosen?'Die aktuelle Gestaltung wird ersetzt. Mit Rückgängig erhältst du deinen bisherigen Entwurf zurück.':`${product.name} · ${product.material}`}</DialogDescription>
      {chosen?<div className="template-confirm"><img src={productImage(chosen.preview)} alt={chosen.name} data-testid="template-confirm-preview"/><strong data-testid="template-confirm-name">{chosen.name}</strong><Button disabled={busy} onClick={()=>apply(chosen)} data-testid="template-confirm-replace">{busy&&<LoaderCircle size={15} className="loading-spin"/>}Gestaltung ersetzen</Button><Button variant="outline" disabled={busy} onClick={()=>setChosen(null)} data-testid="template-confirm-cancel"><ArrowLeft size={14}/>Zurück</Button></div>:<>
        <div className="template-filters"><div className="template-collections" role="group" aria-label="Kollektion">{['all',...collections].map(c=><button key={c} aria-pressed={collection===c} onClick={()=>setCollection(c)} data-testid={`template-collection-${c}`}>{labels[c]||'Alle passenden'}</button>)}</div><div className="template-search-row"><label className="template-search"><Search size={16}/><input type="search" placeholder="Vorlage suchen …" aria-label="Vorlagennamen suchen" value={search} onChange={e=>setSearch(e.target.value)} data-testid="template-search"/></label><select aria-label="Anlass oder Verwendungszweck" value={occasion} onChange={e=>setOccasion(e.target.value)} data-testid="template-occasion"><option value="all">Alle Anlässe</option>{[...new Set((items||[]).map(i=>i.occasion))].sort().map(c=><option key={c}>{c}</option>)}</select></div><p data-testid="template-result-count">{items?`${filtered.length} passende Vorlagen`:'Kollektionen laden …'}</p></div>
        <div className="template-options" data-testid="template-results">{items?filtered.length?filtered.map(item=><button key={item.id} onClick={()=>hasDesign?setChosen(item):apply(item)} disabled={busy} data-testid={`template-${item.id}`}><img loading="lazy" src={productImage(item.preview)} alt={`Vorlage ${item.name} auf ${product.name}`} data-testid={`template-preview-${item.id}`}/><div className="template-card-meta"><span data-testid={`template-material-${item.id}`}>{labels[item.collection]}{item.compact?' · Kompakt':''}</span><strong>{item.name}</strong><small>{item.occasion}</small></div></button>):<p data-testid="templates-empty">Keine passende Vorlage für diese Auswahl.</p>:<p role="status" data-testid="templates-loading">Vorlagen werden vorbereitet …</p>}</div>
      </>}{error&&<p className="property-error" role="alert" data-testid="template-error">{error}</p>}
    </DialogContent></Dialog></>;
};