import { ArrowLeft, ArrowUpRight, Send, Gem, Heart, Sparkles } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { services } from '@/data/services';

const legal = {
  imprint: { title: 'Impressum', description: 'Angaben zum Anbieter', paragraphs: ['ManuCreator – Ideen. Laser. Unikate.', 'Die vollständigen Anbieterangaben, einschließlich Name, ladungsfähiger Anschrift und Kontaktmöglichkeiten, werden vom Betreiber noch ergänzt. Diese Seite stellt noch kein vollständiges Impressum dar.'] },
  privacy: { title: 'Datenschutz', description: 'Hinweise zur Verarbeitung deiner Anfrage', paragraphs: ['Wenn du das Kontaktformular absendest, werden dein Name, deine E-Mail-Adresse, die gewählte Leistung, die Stückzahl und deine Nachricht gespeichert. Diese Angaben dienen ausschließlich der Bearbeitung deines Projekts. Der Versand einer Anfrage löst keine automatische E-Mail aus.', 'Die Übermittlung deiner Angaben erfolgt freiwillig. Bitte gib im Formular keine sensiblen persönlichen Daten an. Die Verarbeitung erfolgt auf Grundlage deiner Einwilligung beziehungsweise zur Durchführung vorvertraglicher Maßnahmen.', 'Du hast im Rahmen der gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung und Datenübertragbarkeit. Eine erteilte Einwilligung kann für die Zukunft widerrufen werden.', 'Die vollständige Datenschutzerklärung mit Angaben zum Verantwortlichen, Kontaktwegen, Hosting, Speicherdauer und gegebenenfalls weiteren Diensten wird noch ergänzt.'] },
};

export const ContentDialog = ({ content, onClose, onRequest, onSelect }) => {
  const type = content?.type;
  const service = content?.service;
  return <Dialog open={!!content} onOpenChange={open => { if (!open) onClose(); }}><DialogContent className={`content-dialog content-${type}`} data-testid="content-dialog">
    {type === 'service' && service && <><div className={`detail-visual${service.original ? ' detail-visual--original' : ''}`}><img src={service.image} alt={service.alt} data-testid="service-detail-image" /></div><div className="detail-copy"><p className="eyebrow" data-testid="service-detail-eyebrow">{service.eyebrow}</p><DialogTitle data-testid="service-detail-title">{service.name}</DialogTitle><DialogDescription className="detail-description" data-testid="service-detail-description">{service.detail}</DialogDescription><div className="material-tags">{service.examples.map((text, i) => <span key={text} data-testid={`service-detail-example-${i}`}>{text}</span>)}</div><Button className="pill" onClick={() => onRequest(service.id)} data-testid="service-detail-inquiry"><Send size={16} fill="currentColor" />Dein Projekt anfragen<ArrowUpRight size={17} /></Button><button className="detail-back" onClick={() => onSelect(null)} data-testid="service-back-to-examples"><ArrowLeft size={15} />Alle Materialien ansehen</button></div></>}
    {type === 'examples' && <><div className="gallery-heading"><p className="eyebrow" data-testid="gallery-eyebrow">MATERIAL TRIFFT IDEE.</p><DialogTitle data-testid="gallery-title">Kleine Details. Große Wirkung.</DialogTitle><DialogDescription data-testid="gallery-description">Ein Einblick in die Möglichkeiten. Was ist deine Idee?</DialogDescription></div><div className="gallery-grid">{services.map(s => <button key={s.id} className={`gallery-item${s.original ? ' gallery-item--original' : ''}`} onClick={() => onSelect(s)} data-testid={`gallery-${s.id}`}><img src={s.image} alt={s.alt} loading="lazy" data-testid={`gallery-image-${s.id}`} /><span>{s.name}<ArrowUpRight size={17} /></span></button>)}</div><p className="gallery-footnote" data-testid="gallery-note">Die Motive dienen als Material- und Gestaltungsinspiration.</p></>}
    {type === 'about' && <><div className="about-visual"><img src="/images/holz.webp" alt="Filigrane Holzgravur mit Lebensbaum" /></div><div className="about-copy"><p className="eyebrow" data-testid="about-eyebrow">DAS IST MANUCREATOR.</p><DialogTitle data-testid="about-title">Deine Ideen.<br />Meine Leidenschaft.</DialogTitle><DialogDescription data-testid="about-description">Hinter ManuCreator steckt die Freude daran, aus einer Idee etwas Echtes zu machen. Etwas, das man anfassen, verschenken und jeden Tag aufs Neue schätzen kann.</DialogDescription><p data-testid="about-text">Ich verbinde kreative Gestaltung mit präziser Lasertechnik und einem Blick fürs Detail. Ob ein persönliches Einzelstück oder eine kleine Serie für dein Unternehmen: Dein Projekt bekommt die Aufmerksamkeit, die es verdient.</p><div className="about-values">{[[Gem, 'Präzision'], [Heart, 'Persönlich'], [Sparkles, 'Einzigartig']].map(([Icon, text], i) => <span data-testid={`about-value-${i}`} key={text}><Icon size={19} strokeWidth={1.5} />{text}</span>)}</div><Button className="pill" onClick={() => onRequest()} data-testid="about-inquiry">Lass uns deine Idee umsetzen<ArrowUpRight size={17} /></Button></div></>}
    {legal[type] && <div className="legal-copy"><p className="eyebrow">MANUCREATOR</p><DialogTitle data-testid="legal-title">{legal[type].title}</DialogTitle><DialogDescription data-testid="legal-description">{legal[type].description}</DialogDescription>{legal[type].paragraphs.map((p, i) => <p key={i} data-testid={`legal-paragraph-${i}`}>{p}</p>)}</div>}
  </DialogContent></Dialog>;
};