import { Minus, Plus } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { services } from '@/data/services';

export const InquiryFields = ({ form, update, disabled }) => (
  <fieldset disabled={disabled} className="inquiry-fields">
    <div className="form-row"><label htmlFor="inquiry-name">Dein Name <span>*</span><Input id="inquiry-name" data-testid="inquiry-name" autoComplete="name" placeholder="Vor- und Nachname" value={form.name} onChange={e => update('name', e.target.value)} minLength={2} maxLength={120} required /></label><label htmlFor="inquiry-email">E-Mail-Adresse <span>*</span><Input id="inquiry-email" data-testid="inquiry-email" type="email" autoComplete="email" placeholder="hallo@beispiel.de" value={form.email} onChange={e => update('email', e.target.value)} maxLength={254} required /></label></div>
    <div className="form-row material-row"><label htmlFor="inquiry-material">Was möchtest du gestalten?<select id="inquiry-material" data-testid="inquiry-material" value={form.material} onChange={e => update('material', e.target.value)}><option value="offen">Noch offen – gerne beraten</option>{services.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label htmlFor="inquiry-quantity">Stückzahl<div className="quantity-control"><button type="button" disabled={form.quantity <= 1 || disabled} onClick={() => update('quantity', Math.max(1, Number(form.quantity) - 1))} aria-label="Stückzahl verringern" data-testid="quantity-decrease"><Minus size={15} /></button><Input id="inquiry-quantity" data-testid="inquiry-quantity" type="number" min="1" max="100000" step="1" value={form.quantity} onChange={e => update('quantity', e.target.value)} required /><button type="button" disabled={form.quantity >= 100000 || disabled} onClick={() => update('quantity', Math.min(100000, Number(form.quantity) + 1))} aria-label="Stückzahl erhöhen" data-testid="quantity-increase"><Plus size={15} /></button></div></label></div>
    <label htmlFor="inquiry-message">Erzähl mir von deiner Idee <span>*</span><Textarea id="inquiry-message" data-testid="inquiry-message" rows={4} placeholder="Was soll entstehen? Hast du schon ein Motiv, bestimmte Maße oder einen Wunschtermin?" value={form.message} onChange={e => update('message', e.target.value)} minLength={10} maxLength={5000} required /></label>
    <div className="honeypot" aria-hidden="true"><label htmlFor="inquiry-website">Website<Input id="inquiry-website" data-testid="inquiry-honeypot" name="website" autoComplete="off" tabIndex={-1} value={form.website} onChange={e => update('website', e.target.value)} /></label></div>
    <p className="inquiry-privacy-notice" data-testid="inquiry-privacy-text">Manuel Bayer · ManuCreator verarbeitet deine Angaben zur Bearbeitung deiner unverbindlichen Anfrage. Einzelheiten findest du in der <a href="/datenschutz" target="_blank" rel="noopener noreferrer" data-testid="inquiry-privacy-link">Datenschutzerklärung</a>. Es erfolgt keine Anmeldung zu Werbung oder Newsletter.</p>
    <details className="form-privacy"><summary data-testid="inquiry-privacy-details">Mehr zum Umgang mit deinen Angaben</summary><p data-testid="inquiry-privacy-details-text">Verantwortlich: Manuel Bayer, Büttgerwald 16, 47877 Willich · info@manucreator.de. Deine Anfrage wird gespeichert. Die Verarbeitung zur Vertragsanbahnung erfolgt nach Artikel 6 Absatz 1 Buchstabe b DSGVO; eine zusätzliche Einwilligung ist dafür nicht erforderlich. Bitte übermittle keine sensiblen Informationen.</p></details>
  </fieldset>
);