import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, ShoppingBag, Minus, Plus, Trash2, Pencil, ShieldCheck, LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useStudio } from '@/components/studio/StudioLayout';
import { PrivateImage } from '@/components/studio/PrivateImage';
import { price, studioApi } from '@/lib/studioApi';

export default function StudioCartPage() {
  const { cart, setCart } = useStudio(), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const change = async (item, quantity) => { setBusy(item.id); setError(''); try { setCart(await studioApi(`/cart/${item.id}`, { method: quantity === 0 ? 'DELETE' : 'PATCH', body: quantity === 0 ? undefined : { quantity } })); } catch (err) { setError(err.message); } finally { setBusy(''); } };
  return <main className="studio-wrap studio-cart-page"><div className="studio-page-heading"><div><p className="eyebrow">DEINE AUSWAHL</p><h1 data-testid="cart-title">Deine Ideen, <em>gut aufgehoben.</em></h1><p data-testid="cart-description">Gespeicherte Entwürfe. Noch kein Auftrag.</p></div><Link className="studio-text-link" to="/gestalten" data-testid="cart-continue"><ArrowLeft size={15} />Weiter gestalten</Link></div>
    {!cart.items.length ? <div className="studio-empty-cart"><ShoppingBag size={40} strokeWidth={1.2}/><h2 data-testid="cart-empty-title">Hier ist Platz für deine erste Idee.</h2><p>Gestalte einen Rohling und lege deinen Entwurf hier ab.</p><Button asChild><Link to="/gestalten" data-testid="cart-empty-create">Mein Unikat gestalten<ArrowRight size={16}/></Link></Button></div> : <div className="studio-cart-layout"><section className="studio-cart-items" aria-label="Entwürfe">{cart.items.map(item => <article className="studio-cart-item" key={item.id} data-testid={`cart-item-${item.id}`}>
      <div className="studio-cart-image"><PrivateImage id={item.draft.render_id} alt={`Gespeicherter Entwurf: ${item.product_name}`} testId={`cart-image-${item.id}`}/></div><div className="studio-cart-details"><span className="studio-material">TESTENTWURF</span><h2 data-testid={`cart-name-${item.id}`}>{item.product_name}</h2><p data-testid={`cart-text-${item.id}`}>{item.draft.design.elements ? item.draft.design.elements.filter(e=>e.kind==='text'&&!e.hidden).map(e=>e.text).join(' · ') || 'Eigenes Motiv' : item.draft.design.text}</p><span className="studio-cart-ai-state" data-testid={`cart-saved-${item.id}`}>Direktvorschau und Gestaltung gespeichert</span><div className="studio-cart-item-actions"><Link to={`/gestalten?draft=${item.draft.id}`} data-testid={`cart-edit-${item.id}`}><Pencil size={13}/>Entwurf öffnen</Link><button onClick={()=>change(item,0)} disabled={!!busy} data-testid={`cart-remove-${item.id}`}><Trash2 size={13}/>Entfernen</button></div></div>
      <div className="studio-cart-quantity"><button onClick={()=>change(item,item.quantity-1)} disabled={!!busy||item.quantity<=1} aria-label="Stückzahl verringern" data-testid={`cart-minus-${item.id}`}><Minus size={14}/></button><span data-testid={`cart-quantity-${item.id}`}>{busy===item.id?<LoaderCircle className="loading-spin" size={14}/>:item.quantity}</span><button onClick={()=>change(item,item.quantity+1)} disabled={!!busy||item.quantity>=20} aria-label="Stückzahl erhöhen" data-testid={`cart-plus-${item.id}`}><Plus size={14}/></button></div><div className="studio-cart-line-price"><strong data-testid={`cart-price-${item.id}`}>{price(item.subtotal_cents)}</strong><small>Beispielpreis</small></div>
    </article>)}</section><aside className="studio-order-summary"><span className="eyebrow">ALLES AUF EINEN BLICK</span><h2>Dein Test-Warenkorb</h2><dl><div><dt>Musterartikel</dt><dd data-testid="cart-count">{cart.count}</dd></div><div><dt>Beispiel-Gesamtwert</dt><dd data-testid="cart-total">{price(cart.total_cents)}</dd></div><div className="studio-zero-pay"><dt>Jetzt zu zahlen</dt><dd data-testid="cart-payable">0,00 €</dd></div></dl><p>Keine Zahlung, kein verbindlicher Kauf und keine Fertigung. Produktmaße und Preise dienen nur als Beispiele.</p><Button asChild className="studio-add-cart"><Link to="/testabschluss" data-testid="cart-checkout">Zum Testabschluss<ArrowRight size={16}/></Link></Button><span className="studio-safe"><ShieldCheck size={15}/>Dein genauer Entwurf bleibt erhalten.</span></aside></div>}
    {error && <p role="alert" className="studio-error" data-testid="cart-error">{error}</p>}
  </main>;
}